/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_metalfabricmod_MetalFabricClientMod */

#ifndef _Included_com_metalfabricmod_MetalFabricClientMod
#define _Included_com_metalfabricmod_MetalFabricClientMod
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_metalfabricmod_MetalFabricClientMod
 * Method:    initMetalBridge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_metalfabricmod_MetalFabricClientMod_initMetalBridge
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
